version: "3.8"
 
services:
  cube:
    image: cubejs/cube:latest
    container_name: cubejs-bug-report
    restart: always
    ports:
      - 3000:3000
      - 4000:4000
      - 15432:5432
    env_file:      
      - .env
    volumes:
      - .:/cube/conf
      - ./db/:/cube/db
